### ISSUE TITLE
Check the number of objects in all relevant Analyzers

### ISSUE THREAD

**Issue by caredg** [JonaJJSJ-crypto/AcausalPOETAnalyzer#1]
The original POET contains a bug: the majority of variables storing the number of ojects does not collect the number that is actually written in the myoutput.root final ntuple file.  For instance, for the tracks, thi line https://github.com/JonaJJSJ-crypto/AcausalPOETAnalyzer/blob/68970b460676683a0ec732f6cb55c10bf64987e1/PhysObjectExtractor/src/TrackAnalyzer.cc#L185
will not record this information correctly.  The original POET has the number of muons corrected, see [this](https://github.com/JonaJJSJ-crypto/AcausalPOETAnalyzer/blob/68970b460676683a0ec732f6cb55c10bf64987e1/PhysObjectExtractor/src/MuonAnalyzer.cc#L232) line.  @JonaJJSJ-crypto can you check this and fix this (if not done already) for all the relevant analyzers, i.e., at least jets, electrons, vertices, etc.

**Comment by JonaJJSJ-crypto** [comment]
This should be already correct in Electrons, Jets, Vertices and the pointed Track analyzers. The solution was using the exact same recommended solution.
