### ISSUE TITLE
Get position of jets in the calorimeters

### ISSUE THREAD

**Issue by caredg** [JonaJJSJ-crypto/AcausalPOETAnalyzer#10]
@JonaJJSJ-crypto, I am not exactly sure how to do this, but I think one thing that could work is to [get the constituents](https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/DataFormats/JetReco/interface/PFJet.h#L165) of the jet, then maybe take the one with highest pT and then from that one obtain the [position at the ecal entrance](https://github.com/cms-sw/cmssw/blob/6d2f66057131baacc2fcbdd203588c41c885b42c/DataFormats/ParticleFlowCandidate/interface/PFCandidate.h#L363). I am not sure if this will work, but maybe we can test it.

**Comment by JonaJJSJ-crypto** [comment]
I think with the new simulations this is possible. Yo can get information on the detectors but in not sure if all that we need, let me check this.

**Comment by caredg** [comment]
@JonaJJSJ-crypto, what happened with this?

**Comment by JonaJJSJ-crypto** [comment]
Included plus the most energetic transverse momentum for comparison
