### ISSUE TITLE
change trigger names

### ISSUE THREAD

**Issue by caredg** [JonaJJSJ-crypto/AcausalPOETAnalyzer#2]
@JonaJJSJ-crypto, this line needs to be changed to reflect the triggers that we are going to use.  ~See [this](https://github.com/JonaJJSJ-crypto/AcausalPOETAnalyzer/blob/a84b9561177e0dae63c1ea0360df8c66b28f6836/PhysObjectExtractor/python/poet_cfg.py#L221)~

https://github.com/JonaJJSJ-crypto/AcausalPOETAnalyzer/blob/a84b9561177e0dae63c1ea0360df8c66b28f6836/PhysObjectExtractor/python/poet_cfg.py#L221

Be careful with the trailing "_v*"

**Comment by caredg** [comment]
sorry the correct link is [this](https://github.com/JonaJJSJ-crypto/Proyecto-de-Tesis/issues/32#issuecomment-922630445)

**Comment by caredg** [comment]
More explicitly, we need:
HLT_Photon36_CaloId10_Iso50_Photon22_CaloId10_Iso50 
HLT_Photon36_CaloId10_Iso50_Photon22_R9Id85 
HLT_Photon36_R9Id85_Photon22_CaloId10_Iso50 
HLT_Photon36_R9Id85_Photon22_R9Id85 
HLT_Photon36_Photon22 
HLT_Photon26_Photon18

**Comment by JonaJJSJ-crypto** [comment]
The needed triggers are now already being stored
