### ISSUE TITLE
Store the appropriate particles in generator info analyzer

### ISSUE THREAD

**Issue by caredg** [JonaJJSJ-crypto/AcausalPOETAnalyzer#3]
https://github.com/JonaJJSJ-crypto/AcausalPOETAnalyzer/blob/f2d1b1375b4f1389e6791d728857fec699361501/PhysObjectExtractor/python/poet_cfg.py#L213

Here we would need the electrons, the Z, the lw electrons

And maybe we could try to store the info of quarks that have the status consistent with having come from the Z decay.

**Comment by JonaJJSJ-crypto** [comment]
The particles that will be store are 11,-11,23,556 and -556, In order to store the last three types of particles was necessary to edit the source code to allow status 0 meaning every status
