### ISSUE TITLE
jetAnalyzsis.log needed

### ISSUE THREAD

**Issue by caredg** [JonaJJSJ-crypto/AcausalPOETAnalyzer#4]
https://github.com/JonaJJSJ-crypto/AcausalPOETAnalyzer/blob/9276df3c3753193b538241111d0a616193a467c7/PhysObjectExtractor/jetAnalyzsis.log#L7

@JonaJJSJ-crypto, is this file needed in the repository? if not, please delete it in the next commit.  
Thanks.

**Comment by JonaJJSJ-crypto** [comment]
Already Removed
