### ISSUE TITLE
Add dxy and maybe the rest of distance variables for tracks

### ISSUE THREAD

**Issue by caredg** [JonaJJSJ-crypto/AcausalPOETAnalyzer#5]
https://github.com/JonaJJSJ-crypto/AcausalPOETAnalyzer/blob/9f562804f434be4d4b3cde1cb097314d93662a57/PhysObjectExtractor/src/TrackAnalyzer.cc#L107
@JonaJJSJ-crypto, creo que sí sería bueno añadir estas variables.

**Comment by JonaJJSJ-crypto** [comment]
Already added ill update if the files have change size
