### ISSUE TITLE
Add beam spot information

### ISSUE THREAD

**Issue by caredg** [JonaJJSJ-crypto/AcausalPOETAnalyzer#8]
@JonaJJSJ-crypto, could you also add beamspot information?  maybe in the electron analyzer?
Note that the container is already [there](https://github.com/cms-legacydata-analyses/PhysObjectExtractorTool/blob/42e213ee9d9a56ce28803b8a8ed5aa58160eac62/PhysObjectExtractor/src/ElectronAnalyzer.cc#L170).  
Actually, some information is [used](https://github.com/cms-legacydata-analyses/PhysObjectExtractorTool/blob/42e213ee9d9a56ce28803b8a8ed5aa58160eac62/PhysObjectExtractor/src/ElectronAnalyzer.cc#L202) already.  But I think it would be useful to really tag the place where the collision happened and check and study that.  For example check how it differs or agrees with the PV of the electrons.

I stole this snippet from somewhere else, but this is the kind of info we might need:

```cpp
reco::BeamSpot vertexBeamSpot= *beamSpotHandle;  

  // store beam spot info 
  Bsp_x = vertexBeamSpot.x0();
  Bsp_y = vertexBeamSpot.y0();
  Bsp_z = vertexBeamSpot.z0();
  Bsp_sigmaz = vertexBeamSpot.sigmaZ();
  Bsp_dxdz = vertexBeamSpot.dxdz();
  Bsp_dydz = vertexBeamSpot.dydz();
  Bsp_widthx = vertexBeamSpot.BeamWidthX();
  Bsp_widthy = vertexBeamSpot.BeamWidthY();
```

Twikis are not loading right now, but more information may be gotten [here](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideBeamSpot) and [here](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideFindingBeamSpot).

**Comment by JonaJJSJ-crypto** [comment]
I have includede all these cuanqitites plus the already stored quantities for transverse impact parameter.
