### ISSUE TITLE
Get position of supercluster for electrons and 

### ISSUE THREAD

**Issue by caredg** [JonaJJSJ-crypto/AcausalPOETAnalyzer#9]
@JonaJJSJ-crypto can we also store the [supercluster position](https://github.com/cms-sw/cmssw/blob/37bf1fa981cca07a2ee330cf20196954dbb5f707/DataFormats/EgammaCandidates/interface/GsfElectron.h#L294) of the electrons?

**Comment by JonaJJSJ-crypto** [comment]
Included position as a 3d vector, It may be needed to take every coordinate later when analyzing.
